### PR TITLE
h4xed in zbar_processor, zbar_symbol_set, and zbar_version...

### PR DESCRIPTION
**Pull request by bambams**
Hacked in the above. Originally with a source zip. Finally got around to working it into the up-to-date code and committing it to a fork. AS IS. ;)

### CODE REVIEW

**Comment by jonasfj** [comment]
Nice... I'll merge it in, when my new webcam arrives... :)
The NativeMethods thing looks nice... And getting version numbers in is probably not a bad idea...

Thanks for the contribution...

**Comment by jonasfj** [comment]
As you've probably seen I've merged in some of the stuff... :)
Where as other parts doesn't appear ready for release. I've done some work on the processor in the branch of the same name... Mostly clean up and copying in documentation from zbar header files...

I don't see much use for SymbolSet, when Zbar.Image already have a property called Symbols of type IEnumerable<Symbol>... List<Symbol> mySymbolSet(myimage.Symbols) would probably do the trick...

By the way, I really like the version thing... That might turn out to be quite useful...
- Again thanks... :)

**Comment by bambams** [comment]
Yes, I have noticed. I wrote the software for j0rb so whatever you decide to do with it is fine with me (and it was just a means to an end for my j0rb so they don't care either). :) Being relatively unfamiliar with libzbar I just basically hacked away at it until it "worked". :P

One thing I noticed is that in at least one copyright header the line read something like:

Copyright [year(s)] [My name] [Your Email address]

That seemed a bit confusing to me (if I didn't know better I might suspect that [Your Email address] was mine). :) It looks like I patched it (forgot all about that...) and you've since merged it (or otherwise fixed it) so all is well. :)

Thanks again for writing this library. :)

**Comment by jonasfj** [comment]
>  It looks like I patched it (forgot all about that...) and you've since merged it (or otherwise fixed it) so all is well. :)
> True, that's was my fault... I merged in your fix and removed my email as it wasn't supposed to be there in the first place...

**Pull request closed without merging**
